### ISSUE TITLE
pip3 install odrive fails on raspian jessie (python 3.4.2)

### ISSUE THREAD

**Issue by sphereinabox** [odriverobotics/ODrive#188]
Raspian Jessie

```
$ sudo pip3 install odrive
Downloading/unpacking odrive
  Downloading odrive-0.4.0.post7.tar.gz (41kB): 41kB downloaded
  Running setup.py (path:/tmp/pip-build-90_mwl60/odrive/setup.py) egg_info for package odrive
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-90_mwl60/odrive/setup.py", line 84, in <module>
        odrive.utils.setup_udev_rules(Logger())
      File "/tmp/pip-build-90_mwl60/odrive/odrive/utils.py", line 154, in setup_udev_rules
        subprocess.run(["udevadm", "control", "--reload-rules"], check=True)
    AttributeError: 'module' object has no attribute 'run'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-90_mwl60/odrive/setup.py", line 84, in <module>

    odrive.utils.setup_udev_rules(Logger())

  File "/tmp/pip-build-90_mwl60/odrive/odrive/utils.py", line 154, in setup_udev_rules

    subprocess.run(["udevadm", "control", "--reload-rules"], check=True)

AttributeError: 'module' object has no attribute 'run'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-90_mwl60/odrive
Storing debug log for failure in /root/.pip/pip.log
```

Checking google it seems the issue is that subprocess.run() is new in python 3.5

**Comment by madcowswe** [comment]
Fixed in v0.4.1 by using `subprocess.check_call` instead of `subprocess.run`.

BTW [Raspbian Stretch](https://www.raspberrypi.org/downloads/raspbian/) is now out.
