### ISSUE TITLE
odrivetool: Invalid path spec "usb"

### ISSUE THREAD

**Issue by kalvdans** [odriverobotics/ODrive#237]
The default path specification seems to be an invalid choice.

```
chn@brahe:~/odrive/ODrive/tools$ ./odrivetool 
ODrive control utility v0.4.3
Traceback (most recent call last):
  File "./odrivetool", line 137, in <module>
    odrive.shell.launch_shell(args, logger, app_shutdown_token)
  File "/home/chn/odrive/ODrive/tools/odrive/shell.py", line 89, in launch_shell
    branding_short="odrv", branding_long="ODrive")
  File "/home/chn/odrive/ODrive/Firmware/fibre/python/fibre/shell.py", line 64, in launch_shell
    logger=logger)
  File "/home/chn/odrive/ODrive/Firmware/fibre/python/fibre/discovery.py", line 109, in find_all
    raise Exception("Invalid path spec \"{}\"".format(search_spec))
Exception: Invalid path spec "usb"
```

The same error on master and devel branch, on Ubuntu bionic, with no odrive connected.

**Comment by kalvdans** [comment]
It was fixed by setting up the correct pip environment. The error message could be improved but not a showstopper, closing bug again.
