### ISSUE TITLE
Account setup issue TLS

### ISSUE THREAD

**Issue by timsummerer** [odriverobotics/ODrive#315]
I just installed the `odrive-bin` package (version 0.2.1) from the AUR (Arch User Repository).
After logging into my Google account and pressing the approve button for ODrive the following Error message appears.
The OS is Arch Linux running GNOME Desktop.
Killing the odrive process and trying to run the setup again (3 times) results in this issue every time.

`Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1086:19)
    at Object.onceWrapper (events.js:273:13)
    at TLSSocket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

**Comment by timsummerer** [comment]
Sorry wrong ODrive.
