### ISSUE TITLE
pip3 couldn't install odrivetool when old setuptools (version 41.4.0) was around

### ISSUE THREAD

**Issue by tobbelobb** [odriverobotics/ODrive#565]
This probably isn't a bug in odrive, rather an incompatibility between odrive/setuptools versions, probably due to a bug in setuptools 41.4.0. However, I went here first in search of a quick solution, so I thought I'd put the workaround here, in case others do the same.

**Describe the bug**
When installing odrivetool on an Ubuntu 18.04 system, I was required to upgrade setuptools separtely first.

**To Reproduce**
```
sudo -H pip3 uninstall setuptools
sudo -H pip3 install setuptools==41.4.0
sudo -H pip3 install --upgrade odrive
```

**Expected behavior**
```
Successfully installed <...> odrive-0.5.1.post0
```

**Observed behaviour**
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4sfstfg5/odrive/setup.py", line 123, in <module>
        classifiers = [],
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 55, in run
        self.build_package_data()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_py.py", line 126, in build_package_data
        srcfile in self.distribution.convert_2to3_doctests):
    TypeError: argument of type 'NoneType' is not iterable
```

**Workaround**
```
sudo -H pip3 install --upgrade setuptools
sudo -H pip3 install --upgrade odrive
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - odrivetool Version ODrive control utility v0.5.1.post0

**Additional context**
The problem is solved, and there's nothing to do for odrive maintainers here.

**Comment by Wetmelon** [comment]
Thanks for the info and workaround.  We'll keep this in mind if people have issues.
