### ISSUE TITLE
odrivetool: Error on drv-status

### ISSUE THREAD

**Issue by liborw** [odriverobotics/ODrive#743]
**Describe the bug**
drv-status produce following error:

```
$ odrivetool drv-status
Waiting for ODrive...
Traceback (most recent call last):
  File "/home/wagnelib/Work/protocols/2024-03-12_Odrive/env/bin/odrivetool", line 216, in <module>
    print_drv_regs("Motor 0", my_odrive.axis0.motor)
  File "/home/wagnelib/Work/protocols/2024-03-12_Odrive/env/lib/python3.11/site-packages/odrive/utils.py", line 449, in print_drv_regs
    fault = motor.gate_driver.drv_fault
            ^^^^^^^^^^^^^^^^^
AttributeError: 'anonymous_interface_127888826724624' object has no attribute 'gate_driver'
```

**To Reproduce**

Call:
```
$ odrivetool drv-status
```

**Expected behavior**
Print drv status.

**Desktop (please complete the following information):**
 - OS: 
```
$ uname -a
Linux *** 6.6.20-1-lts #1 SMP PREEMPT_DYNAMIC Sun, 03 Mar 2024 07:25:31 +0000 x86_64 GNU/Linux
```
 - odrivetool Version (`odrivetool --version`)

```
$ odrivetool --version
ODrive control utility v0.6.8
```
 - odrive board: Odrive S1

**Additional context**
None

**Comment by samuelsadok** [comment]
Thanks for the heads-up. This is a quite old command that hasn't been maintained for a while, I actually forgot it's there. I'll make a note to retire it.

You can instead look up DRV fault details by typing `dump_errors(odrv0)` or `odrv0.axis0.last_drv_fault` inside the interactive `odrivetool` console.

That said, on new-gen ODrives (S1, Pro, ...) you should not be getting DRV faults during normal operation (or at all, for that matter). if you do, please let us know (e.g. here or on Discord or info@odriverobotics.com).
